#!/bin/sh
set -e

. ~/.sh-todo

PAT="$*"

if [ -z "$PAT" ]; then
  echo "Error: no task to mark done specified" >&2
  exit 1
fi

echo -n > "$TODO_F.tmp"

while read -r LINE; do
  if [ "${LINE#$TODO_PREFIX*$PAT}" != "$LINE" ]; then
    # use printf to ensure backslash escapes are interpreted
    printf "• $BEGIN_DONE${LINE#$TODO_PREFIX}$END_DONE\n"
    LINE="$DONE_PREFIX${LINE#$TODO_PREFIX} ($(date "$DATE_FMT"))"
    echo $LINE >> $TODONE_F
  fi
  echo $LINE >> "$TODO_F.tmp"
done < $TODO_F

mv "$TODO_F.tmp" $TODO_F
