#!/bin/sh
# Part of sh-todo:
# https://github.com/asb/sh-todo
set -e

. ~/.sh-todo

PAT="$*"

if [ -z "$PAT" ]; then
  printf "Error: no task to mark done specified\n" >&2
  exit 1
fi

touch "$TODO_F.tmp"

while read -r LINE; do
  if [ "${LINE#TODO *$PAT}" != "$LINE" ]; then
    TASK="${LINE#TODO }"
    printf "• $BEGIN_DONE%s$END_DONE\n" "$TASK"
    LINE=$(printf "DONE %s ($(date "+%Y-%m-%d %R"))" "$TASK")
    printf "%s\n" "$LINE" >> "$TODONE_F"
  fi
  printf "%s\n" "$LINE" >> "$TODO_F.tmp"
done < "$TODO_F"

mv "$TODO_F.tmp" "$TODO_F"
