#!/bin/sh
# Part of sh-todo:
# https://github.com/asb/sh-todo
set -e

. ~/.sh-todo

NEW_TODO="$*"

# if no arguments, then print todo list instead
if [ -z "$NEW_TODO" ]; then
  while read -r LINE; do
    if [ "${LINE#$DONE_PREFIX}" != "$LINE" ]; then
      # use printf to ensure backslash escapes are interpreted
      printf "• $BEGIN_DONE${LINE#$DONE_PREFIX}$END_DONE\n"
    else
      echo "• ${LINE#$TODO_PREFIX}"
    fi
  done < $TODO_F
  exit 0
fi

echo "$TODO_PREFIX$NEW_TODO" >> $TODO_F
