#!/bin/sh
# Part of sh-todo:
# https://github.com/asb/sh-todo
#
# Remove all DONE lines from $TODO_F. All such lines will already have been 
# added to $TODONE_F
set -e

. ~/.sh-todo

> "$TODO_F.tmp"

while read -r LINE; do
  if [ "${LINE#DONE }" != "$LINE" ]; then
    printf "• $BEGIN_DONE%s$END_DONE\n" "${LINE#DONE }"
  else
    printf "%s\n" "$LINE" >> "$TODO_F.tmp"
  fi;
done < "$TODO_F"

mv "$TODO_F.tmp" "$TODO_F"
