#!/bin/sh
# Remove all DONE lines from $TODO_F. All such lines will already have been 
# added to $TODONE_F
set -e

. ~/.sh-todo

echo -n > "$TODO_F.tmp"

# intentional useless use of cat (see README)
cat $TODO_F | while read -r LINE; do
  if [ "${LINE#$DONE_PFX}" != "$LINE" ]; then
    echo "• $BEGIN_DONE${LINE#$DONE_PFX}$END_DONE"
  else
    echo $LINE >> "$TODO_F.tmp"
  fi;
done

mv "$TODO_F.tmp" $TODO_F
