#!/bin/sh
# Remove all DONE lines from $TODO_F. All such lines will already have been 
# added to $TODONE_F
set -e

. ~/.sh-todo

echo -n > "$TODO_F.tmp"

while read -r LINE; do
  if [ "${LINE#$DONE_PREFIX}" != "$LINE" ]; then
    echo "• $BEGIN_DONE${LINE#$DONE_PREFIX}$END_DONE"
  else
    echo $LINE >> "$TODO_F.tmp"
  fi;
done < $TODO_F

mv "$TODO_F.tmp" $TODO_F
