#!/bin/sh
# Part of loamok/sh-todo:
# https://github.com/loamok/sh-todo
# forked from asb/sh-todo
# https://github.com/asb/sh-todo
#
# Activate (copy) the sh-todo file in the user home

CP="cp -a"

#Destination of installation
DESTETC=/etc/default


$CP $DESTETC/sh-todo ~/.sh-todo
